server:
  port: 50080

project:
  name: ${spring.application.name}

spring:
  application:
    name: test-sentinel-01
  cloud:
    sentinel:
      transport:
        dashboard: localhost:50089
        port: 8791

#csp:
#  sentinel:
#    dashboard:
#      server: localhost:50089
#    api:
#      port: 50082

knife4j:
  enable: true
