server:
  port: 50080

# dashboard-2
project:
  name: ${spring.application.name}

spring:
  application:
    name: test-sentinel-01
  cloud:
    sentinel:
      # dashboard-1
      transport:
        dashboard: localhost:50089
        port: 8791

knife4j:
  enable: true
